### PR TITLE
Using NullLogger types from Logging.Abstractions

### PR DESCRIPTION
**Pull request by ajaybhargavb**
aspnet/Logging#571
@Eilon

### CODE REVIEW

**Comment by hishamco** [comment]
CI builds are failed

**Comment by Eilon** [comment]
Also, AppVeyor/Travis failing??

**Comment by ajaybhargavb** [comment]
Merging now. It should pass on the CI

**Comment by natemcmaster** [comment]
It looks like it's still failing on internal CI.

```
ResourceManagerStringLocalizerTest.cs(12,36): error CS0234: The type or namespace name 'Testing' does not exist in the namespace 'Microsoft.Extensions.Logging' (are you missing an assembly reference?) [C:\BuildAgent\work\db3ec317da5cf2f9\.r\Localization\test\Microsoft.Extensions.Localization.Tests\Microsoft.Extensions.Localization.Tests.csproj]
ResourceManagerStringLocalizerTest.cs(230,17): error CS0246: The type or namespace name 'TestSink' could not be found (are you missing a using directive or an assembly reference?) [C:\BuildAgent\work\db3ec317da5cf2f9\.r\Localization\test\Microsoft.Extensions.Localization.Tests\Microsoft.Extensions.Localization.Tests.csproj]
```

**Comment by Eilon** [comment]
@ajaybhargavb ?

**Comment by ajaybhargavb** [comment]
https://github.com/aspnet/Localization/pull/342

**Comment by hishamco** [comment]
I notice that too after @ajaybhargavb first commit, but he fix it in the next one

**Pull request merged**
