### PR TITLE
Disable API Check in a project with untracked breaking changes

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
Will go in before fix for aspnet/KoreBuild#143

**Comment by ryanbrandenburg** [comment]
Seems straightforward. :shipit:

**Comment by dougbu** [comment]
See aspnet/BuildTools#205 for more context

**Comment by dougbu** [comment]
@ryanbrandenburg did you approve?

**Comment by dougbu** [comment]
9408b5b

**Pull request closed without merging**
