### PR TITLE
Fix issue #421

### PR DESCRIPTION
**Pull request by hishamco**
Address issue #421

### CODE REVIEW

**Comment by hishamco** [comment]
Is there any need for unnecessary checks in the constructors?

/cc @ryanbrandenburg @pranavkm

**Comment by pranavkm** [comment]
The null check? I'd leave them in for the sake of consistency.

**Comment by hishamco** [comment]
Yep, but I don't think there's a need for some of them while the base class is already did the same check. Am I right?

**Comment by pranavkm** [comment]
👍 @Eilon good to merge?

**Comment by hishamco** [comment]
Any updates on this? ⌚️

**Comment by hishamco** [comment]
@Eilon could you please merge this and close the related issue

**Comment by Eilon** [comment]
@hishamco sorry for the delay, I've assigned this to @ryanbrandenburg to review.

**Pull request merged**
