### PR TITLE
Fix namespace typo

### PR DESCRIPTION
**Pull request by hishamco**
Base on my commit https://github.com/aspnet/Localization/commit/5f83c0df434d117abbca89dc7b5e2e2286d738c3, I forgot to rename the namespace of ```ResourceManagerStringLocalizerTest``` class, so i did this fix

### CODE REVIEW

**Comment by kirthik** [comment]
[:shipit]. Will merge

**Comment by hishamco** [comment]
:watch: 
BTW is there someone will look into Localization repo PRs while Damian is busy

**Comment by kirthik** [comment]
merged 2faf31727ed5cdded889239892fa3ce25966ee36

**Pull request closed without merging**
