### PR TITLE
Update hyperlink for README.md

### PR DESCRIPTION
**Pull request by JoeSiew**
Hi, I am new to github; Hence please correct me if my pull request format is wrong.
I notice that the link for Localization Samples is not working leading to error 404. Therefore, I fixed the hyperlink for Localization.StarterWeb, Localization.EntityFramework, Localization.CustomResourceManager

### CODE REVIEW

**Comment by hishamco** [comment]
Thanks @JoeSiew, this is happen after branches rename.
One little commit you can change the target branch to `release/2.2`

**Comment by JoeSiew** [comment]
Hi @hishamco , the target branch of release/2.2 hyperlink is not working as well. Do you want me to update the hyperlink?

**Comment by Eilon** [comment]
BTW we might not need this PR because we have a bot that sends PRs from release/2.2 to master. I'll keep this open for a while to see if we need it.

**Comment by Eilon** [comment]
OK the bot did pick it up here: https://github.com/aspnet/Localization/pull/451

So I'm closing this PR so we can avoid merge conflicts. Thanks!

**Pull request closed without merging**
