### PR TITLE
Switch async void to async Task

### PR DESCRIPTION
**Pull request by pranavkm**
cc @rynowak

### CODE REVIEW

**Comment by davidfowl** [comment]
yass

**Comment by rynowak** [comment]
Might be worth doing a global search in Universe. I fixed a few of these in MVC a little while back.

**Comment by rynowak** [comment]
:shipit:

**Comment by pranavkm** [comment]
Yup, I think there's a few more in this repo. Additionally a bunch more in stale repos that I've been pestering @Eilon to delete.

**Pull request closed without merging**
