### PR TITLE
Add EntityFramework Localization Sample

### PR DESCRIPTION
**Pull request by hishamco**
I see many users asking about localization sources, and how to use other sources such as json, database .. etc instead of resx files. I provide this example to use EntityFramework as source

### CODE REVIEW

**Comment by hishamco** [comment]
Can we consider this a helpful sample, that will give the developers a glimpse to how extend localization APIs to create a various data sources 
/cc @kirthik @Eilon

**Comment by davidfowl** [comment]
This sorta thing belongs in Entropy.

**Comment by hishamco** [comment]
@davidfowl but there are many question that i saw about change localization store, this issue #105 that let me take the initiative to provide such a sample in this repo

**Comment by davidfowl** [comment]
@hishamco That's great but I'm asking you to move it to Entropy. Where all of our other examples like this belong.

**Comment by hishamco** [comment]
ok @davidfowl I will move there, and i will mention it here
thanks

**Comment by hishamco** [comment]
Based on @davidfowl suggestion, i moved the PR to https://github.com/aspnet/Entropy/pull/76

**Pull request closed without merging**
