### PR TITLE
Microsoft.Framework.Localization.Test -> Microsoft.Framework.Localization.Tests

### PR DESCRIPTION
**Pull request by hishamco**
According to the guidelines https://github.com/aspnet/Home/wiki/Engineering-guidelines#solution-and-project-folder-structure-and-naming, we should rename the test project to ```Microsoft.Framework.Localization.Tests``` instead of ```Microsoft.Framework.Localization.Test```

/cc @Eilon

### CODE REVIEW

**Comment by Eilon** [comment]
Does the SLN need to change too?

**Comment by hishamco** [comment]
You are right @Eilon, I update the PR, let me know if you have any kind of feedback, or i will squash the commits

**Comment by Eilon** [comment]
I don't see the change to the SLN file itself. It's pointing to the old file name.

**Comment by Eilon** [comment]
And old path.

**Comment by hishamco** [comment]
Strange!! I renamed the .xproj, it appears in File changed tab

**Comment by hishamco** [comment]
Ok got it :smile:

**Comment by Eilon** [comment]
Looks good. @kirthik can you take a look and merge?

**Comment by kirthik** [comment]
Sure. I will do that.

**Comment by kirthik** [comment]
merged 5f83c0df434d117abbca89dc7b5e2e2286d738c3

**Pull request closed without merging**
