### PR TITLE
Fix test failures

### PR DESCRIPTION
**Pull request by kichalla**
@Eilon @javiercn @muratg

### CODE REVIEW

**Comment by muratg** [comment]
:shipit:

**Comment by Eilon** [comment]
:shipit:

**Comment by JunTaoLuo** [comment]
@kichalla which approach should we go with, this one or #220?

**Comment by javiercn** [comment]
:shipit:

**Comment by Eilon** [comment]
@JunTaoLuo I like the approach here a bit more. But could have gone either way.

**Pull request merged**
