### PR TITLE
Fix to google chrome with the header zh-Hans-CN

### PR DESCRIPTION
**Pull request by Kagamine**
The most of browsers will detect the accept lang into zh or zh-CN, but in chrome it will be zh-Hans-CN.
By the way, I am not suggest put cultures in a class, why not put them into the resx? I think a resource file contains the cultures which supported in the file is better.

### CODE REVIEW

**Comment by hishamco** [comment]
@Kagamine the list already updated in the PR #101 , furthermore the list is updated by running ```CultureInfoGenerator``` command not by adding entries directly to the list

thanks

**Comment by hishamco** [comment]
Your thoughts @DamianEdwards

**Comment by Kagamine** [comment]
There were some wrong with PR #101 with line 823 824

```
+            "zh-Hans-HK",
+            "zh-Hans-MO",
```

It should be zh-Hant-HK and zh-Hant-MQ and missing zh-Hans-CN zh-Hant-TW

**Comment by Kagamine** [comment]
I will close this pr and make a new. there were something wrong with it.

**Comment by hishamco** [comment]
@kagamine  these culture generated by tool not by me :smile:

**Pull request closed without merging**
